### ISSUE TITLE
Dragging a magnet doesn't always put it on top, it maintains its z coordinates, should increase it to the max when selected so it can be on top of all the magnets

### ISSUE THREAD

**Issue by hrousley** [hrousley/interactive-magnets#7]

**Comment by wernull** [comment]
A few ideas on this one:
1) Keep a global iterator and add it here https://github.com/hrousley/interactive-magnets/blob/master/main.js#L46. Every time something gets clicked it gets 10001, then the next 10002...
2) No css z-index, pop and push the dom element causing it to go to the end and natural showing up on top of the others

**Comment by wernull** [comment]
@hrousley ^
